fixed autoscaling bug and updated hpa sample
spinkube/spin-operator pull request #270
Opened 2024-07-10 20:09 UTC by asteurer

2024-07-10 23:24 UTC, asteurer commented
@bacongobbler @calebschoepp I removed the requirements for a minimum pod count, but I'm running into an issue with `spec.replicas`. When I don't set the replica field, all resources are created; however, I can't port-forward the service, which is how I'm testing the scaling capabilities. Any thoughts?

2024-07-10 23:25 UTC, michelleN reviewed
@asteurer is there an issue I can look at to understand the bug?

2024-07-10 23:27 UTC, michelleN commented
>@asteurer is there an issue or thread I can look at to understand the bug?

nvm found #24 !

2024-07-11 16:11 UTC, calebschoepp commented on config/samples/hpa.yaml
> +  replicas: 1
@bacongobbler says:
> Shouldn't this be removed if both `minReplicas` and `maxReplicas` are set?

2024-07-11 16:11 UTC, calebschoepp commented on internal/controller/spinapp_controller.go
> +	replicas := app.Spec.Replicas
@bacongobbler says:
> related to the above comment RE: min/maxReplicas, shouldn't this be nil if either of those are set?
> 
> If only minReplicas is set (is that valid?), should this be set to minReplicas as a starting value?
> If only maxReplicas is set, should this be set to 1 (or possibly nil, assuming we can scale to zero)?

2024-07-11 16:13 UTC, calebschoepp commented on api/v1alpha1/spinapp_types.go
> +	Selector string `json:"selector"`
@endocrimes would we have to make this optional to support runtimes where this selector is meaningless? Or is setting it to the empty string sufficient.

2024-07-11 16:14 UTC, calebschoepp commented
> @bacongobbler @calebschoepp I removed the requirements for a minimum pod count, but I'm running into an issue with `spec.replicas`. When I don't set the replica field, all resources are created; however, I can't port-forward the service, which is how I'm testing the scaling capabilities. Any thoughts?

Maybe you can't port forward the service because the replicas defaults to zero, so there are no pods, so there is nothing to port forward. It's a bit circular haha.

You could try playing with KEDA scaling on some external factor like messages in a queue. That way to generate load you just put a bunch of messages in a queue and then it would scale it up from zero.

2024-07-11 17:01 UTC, asteurer commented
> > Maybe you can't port forward the service because the replicas defaults to zero, so there are no pods, so there is nothing to port forward. It's a bit circular haha.
>

Shouldn't there be at least 1 pod since we set a minReplicas? If so, I'm not clear on how we would reference the HPA in the SpinApp deployment haha

2024-07-12 17:48 UTC, calebschoepp commented
> Shouldn't there be at least 1 pod since we set a minReplicas? If so, I'm not clear on how we would reference the HPA in the SpinApp deployment.
> 
> Also, `k scale spinapp` does work with the updated minimum pod count logic

[This](https://stackoverflow.com/questions/61596711/in-kubernetes-how-can-i-scale-a-deployment-to-zero-when-idle) looks relevant.

2024-08-13 16:33 UTC, calebschoepp requested changes
No new comments from me. I just want you to address @bacongobbler's comments

2024-08-13 16:33 UTC, calebschoepp commented on config/samples/hpa.yaml
> +  replicas: 1
@asteurer ?

2024-08-13 16:33 UTC, calebschoepp commented on internal/controller/spinapp_controller.go
> +	replicas := app.Spec.Replicas
@asteurer ?

2024-08-20 16:47 UTC, asteurer commented
There's a bug in SpinKube that is preventing metrics from being properly emitted from Spin applications, which is preventing autoscaling, and is making it impossible for me to test. Kate Goldenring is working with jsturtevant (slack handle) from MS to get this fixed.

2024-09-22 03:20 UTC, closed without merging