add release process
spinkube/spin-operator pull request #312
Opened 2024-09-06 18:07 UTC by bacongobbler

Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>

2024-09-06 18:09 UTC, calebschoepp commented on RELEASE.md
> +npm run generate:crd:reference
I don't think we actually want to do this. It seems like we don't check in the reference, we just rely on the CI to generate it. It's just important that we bump the version in that generate script.

2024-09-06 18:22 UTC, adamreese approved these changes

2024-09-06 18:29 UTC, calebschoepp requested changes
One thing to fix

2024-09-06 18:31 UTC, calebschoepp approved these changes

2024-09-07 14:10 UTC, endocrimes approved these changes

2024-09-09 14:58 UTC, merged