Support runtime config in the spintainer executor
spinkube/spin-operator pull request #320
Opened 2024-09-20 21:28 UTC by calebschoepp

Closes #319.

I tested locally to make sure that this works both when runtime config is specified and when it isn't.

2024-09-22 09:12 UTC, endocrimes commented
Could you make sure this is covered by tests at the same time?

(I'm a bit worried about spintainer feature drift because I assume it'll be used much less frequently, covering in tests for the big things should help us there 😅)

2024-09-24 19:05 UTC, calebschoepp commented
@endocrimes I've added some tests.

2024-09-24 19:19 UTC, endocrimes requested changes
Some blocking changes in the tests (timeouts and validity of a couple of the checks) otherwise LGTM

2024-09-24 19:19 UTC, endocrimes commented on e2e/redis_test.go
> +				wait.WithInterval(30*time.Second),
```suggestion
				wait.WithInterval(time.Second),
```

30 seconds between checks is a _really_ long time (especially as the first check doesn't happen until after that interval) - and the check is ~free, so cut this down.

2024-09-24 19:19 UTC, endocrimes commented on e2e/redis_test.go
> +				wait.WithInterval(30*time.Second),
```suggestion
				wait.WithInterval(500*time.Millisecond),
```

this should already be true before the check above completes, so make this be much faster

2024-09-24 19:19 UTC, endocrimes commented on e2e/redis_test.go
> +				wait.WithInterval(30*time.Second),
```suggestion
				wait.WithInterval(500*time.Millisecond),
```

as above

2024-09-24 20:13 UTC, calebschoepp commented
Nice catch @endocrimes, I made those fixes to the spintainer e2e too and overall this shaved 4 minutes off the e2e tests.

2024-09-24 21:33 UTC, endocrimes approved these changes
✨

2024-09-24 21:33 UTC, merged